import Head from "next/head";
import Link from "next/link";


import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Asteria GL
          </h1>
          <Link href="/getstarted">
            <h2 className="text-white text-2xl font-bold">Start playing Asteria </h2>
          </Link>
        
          <Link href="/admin">
            <h2 className="text-white text-2xl font-bold"> Link to Asteria Admin Page - find deploy pellet here </h2>
          </Link>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
}
